// <auto-generated />
using Bitnovo.Banking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Bitnovo.Banking.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Bitnovo.Banking.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CustomerId");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Bitnovo.Banking.Domain.Entities.Account", b =>
                {
                    b.OwnsOne("Bitnovo.Common.PositiveDecimal", "Balance", b1 =>
                        {
                            b1.Property<int>("AccountId");

                            b1.Property<decimal>("Value")
                                .HasColumnName("Balance");

                            b1.HasKey("AccountId");

                            b1.ToTable("Accounts");

                            b1.HasOne("Bitnovo.Banking.Domain.Entities.Account")
                                .WithOne("Balance")
                                .HasForeignKey("Bitnovo.Common.PositiveDecimal", "AccountId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Bitnovo.Common.StringValue", "Number", b1 =>
                        {
                            b1.Property<int>("AccountId");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("Number");

                            b1.HasKey("AccountId");

                            b1.ToTable("Accounts");

                            b1.HasOne("Bitnovo.Banking.Domain.Entities.Account")
                                .WithOne("Number")
                                .HasForeignKey("Bitnovo.Common.StringValue", "AccountId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
