// <auto-generated />
using Bitnovo.Customers.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Bitnovo.Customers.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200626020300_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Bitnovo.Customers.Domain.Aggregates.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Bitnovo.Customers.Domain.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CustomerId");

                    b.Property<int>("Role");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Bitnovo.Customers.Domain.Aggregates.Customer", b =>
                {
                    b.OwnsOne("Bitnovo.Customers.Domain.Aggregates.Email", "Email", b1 =>
                        {
                            b1.Property<int>("CustomerId");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("Email");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.HasOne("Bitnovo.Customers.Domain.Aggregates.Customer")
                                .WithOne("Email")
                                .HasForeignKey("Bitnovo.Customers.Domain.Aggregates.Email", "CustomerId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Bitnovo.Common.StringValue", "FirstName", b1 =>
                        {
                            b1.Property<int>("CustomerId");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("FirstName");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.HasOne("Bitnovo.Customers.Domain.Aggregates.Customer")
                                .WithOne("FirstName")
                                .HasForeignKey("Bitnovo.Common.StringValue", "CustomerId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Bitnovo.Common.StringValue", "Surname", b1 =>
                        {
                            b1.Property<int>("CustomerId");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("Surname");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.HasOne("Bitnovo.Customers.Domain.Aggregates.Customer")
                                .WithOne("Surname")
                                .HasForeignKey("Bitnovo.Common.StringValue", "CustomerId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Bitnovo.Customers.Domain.Aggregates.User", b =>
                {
                    b.HasOne("Bitnovo.Customers.Domain.Aggregates.Customer", "Customer")
                        .WithOne("User")
                        .HasForeignKey("Bitnovo.Customers.Domain.Aggregates.User", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Bitnovo.Common.StringValue", "Password", b1 =>
                        {
                            b1.Property<int>("UserId");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("Password");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.HasOne("Bitnovo.Customers.Domain.Aggregates.User")
                                .WithOne("Password")
                                .HasForeignKey("Bitnovo.Common.StringValue", "UserId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Bitnovo.Common.StringValue", "Username", b1 =>
                        {
                            b1.Property<int>("UserId");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("Username");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.HasOne("Bitnovo.Customers.Domain.Aggregates.User")
                                .WithOne("Username")
                                .HasForeignKey("Bitnovo.Common.StringValue", "UserId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
